FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD service.jar /opt/service/
EXPOSE 8080
WORKDIR /opt/service/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "service.jar"]
